# Generated by Django 4.0.5 on 2023-07-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
